### ISSUE TITLE
Update to Aurora makes Scripts Obsolete

### ISSUE THREAD

**Issue by elemated** [VoronFX/Aurora#1]
Hi @VoronFX ,

I love your scripts and used them for months with Aurora! Unfortunately, the dev just updated the app in the most recent prerelease, so all old scripts are now obsolete and must be updated to implement the IEffectScript interface :(. [https://github.com/antonpup/Aurora/issues/690](url) I wouldn't know the first thing about that, so I was wondering if it would be possible for you to update them? I used PingPulser religiously... Thanks!

**Comment by VoronFX** [comment]
I've not seen the changes in Aurora yet, but I am pretty sure there is nothing difficult. Depending on my laziness I will update scripts today or this week. But will not promise =).
Also there is some idea on improving PingPulser, maybe it's a good time for implementing it...

**Comment by elemated** [comment]
@VoronFX Great! Whether you get to it or not, your scripts are awesome, and thanks for making them!

**Comment by icexuick** [comment]
Would awesome, looking forward to implement this in my own setup.
I'll be waiting for your next update for 0.6.0b (beta).
Keep up the good work!

**Comment by VoronFX** [comment]
New scripts are released! Not to copy, read more detailed message in this thread #2 .
