### ISSUE TITLE
Needs update for new fork

### ISSUE THREAD

**Issue by Aytackydln** [VoronFX/Aurora#13]
Hello, I'm the new maintainer of aurora. Sorry I broke your scripts :) But they are very simple to fix. Can you update your release?

https://github.com/Aurora-RGB/Aurora/issues/61

**Comment by VoronFX** [comment]
Hi. Didn't even knew there is a new fork out there. Haven't checked the mail about Aurora for a while. Yet I am still alive.
I've published new script version with your changes, though previous seems also works with current version of your fork.
After all these years I am still using the my scripts, just have nothing to add to them, he he )

**Comment by Aytackydln** [comment]
Well, I updated aurora to .net 6 and script loading is broken at the moment. Loading .cs directly crashes whole application, gotta change it to compiling dll then loading the dll. Since I haven't heard from you, I've included your scripts to Aurora by default so people can use it.

You can decide how to progress about your scripts when I fix script loading. I can remove them by default or you can make PR directly to repository

**Comment by VoronFX** [comment]
Cool. Let's keep them included by default for now, this shouldn't break existing profiles for people. I have no plans for maintaining them actively in near future. Also I don't have any update ideas, they looks pretty complete to me and cover all my personal needs.
If help will needed with them, feel free to reach out, I will try to find some time for this.
Thanks for your work!
