### ISSUE TITLE
Assigning the PerfEffect for more than 5 CPU Cores impossible in Aurora

### ISSUE THREAD

**Issue by obstriegel** [VoronFX/Aurora#4]
I tried using your script and wanted to add more indicators for more CPU Cores.
I put them on F1 - F4 like in your video. Then I add another Script Layer, put it on F5, and it works.

Now when I try to add a 6th ScriptLayer with the PerfEffect for another core that Layer is "linked" to the last layer created. Every change I make on that new layer is also made in the last created layer and vice versa. Just as both layers were one object in memory.

I checked the created .json file and while Layer "CPU Core 5" and "CPU Core 6" appear to be different items there it is impossible to configure them individually in Aurora.

I am not sure if this is a bug in Aurora itself or in the script.

**Comment by VoronFX** [comment]
You are right, such problem exists. Sometimes new created layer become linked. 
The API that Aurora provides is a bit raw and wasn't made with idea of multiple copies of the same layer. 
So I had to use some workarounds to make it work.

There is workaround as I remember. 
After restarting Aurora these layers should be no more linked.
You can create several layers at once for future and then restart Aurora once to be sure that you will not get linked layers.

Unfortunately I am too busy now for investigating this and catching this bug.
But anyway thank you for reminder that it exists. Maybe some day... )

**Comment by snappyapple632** [comment]
This was a bug in Aurora which has since been fixed.
