### ISSUE TITLE
Request: Monitor multiple drives

### ISSUE THREAD

**Issue by TrainerOrange** [VoronFX/Aurora#9]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Feature request)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Please include any logs, screenshots, or files that are related to this issue:
https://imgur.com/44zof9y

Is it possible to monitor multiple drives simultaniously. Currently I can only find an option for the System drive, I would also like to monitor my D: and E; drives however. I am not too fluent in C#, however I was able to add it in an older version of your software (before the 6.0 beta update of Aurora).

I am using the V1.0 Beta 8 version of your software and V6.3.0 of Aurora.

Any help is appreciated!

**Comment by sellet** [comment]
Hope I'm not too late.

I have set up this way for a while and I can monitor both disks independently.
![image](https://user-images.githubusercontent.com/49080137/55263877-47168e80-5251-11e9-93bb-9c50e0e29b52.png)

![image](https://user-images.githubusercontent.com/49080137/55263937-71684c00-5251-11e9-86a9-72b01f60209b.png)
